// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace LP_API_Implementation.LpApi.Models
{
    public partial class Order
    {
        

        [Required]
		[JsonProperty("orderType")]
        public string OrderType { get; set; }

        [Required]
		[JsonProperty("createdAt")]
        public string CreatedAt { get; set; }

        [Required]
		[JsonProperty("confirmationNumber")]
        public string ConfirmationNumber { get; set; }


		[JsonProperty("data")]
        public Data Data { get; set; }
    } // end class

} // end Models namespace

