// Template: Models (ApiEnum.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace LP_API_Implementation.LpApi.Models
{
    public enum StatusMessage
    {
		SUCCESS, UNKNOWN_MEMBER, MAXIMUM_ATTEMPTS_EXCEEDED, INELIGIBLE    
    }

}
