// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace LP_API_Implementation.LpApi.Models
{
    public partial class Transact
    {
        

        [Required]
		[JsonProperty("memberId")]
        public string MemberId { get; set; }

        [Required]
		[JsonProperty("amount")]
        public int Amount { get; set; }


		[JsonProperty("pic")]
        public string Pic { get; set; }


		[JsonProperty("transactionId")]
        public string TransactionId { get; set; }


		[JsonProperty("bonus")]
        public bool? Bonus { get; set; }

        [Required]
		[JsonProperty("callback")]
        public string Callback { get; set; }


		[JsonProperty("order")]
        public Order Order { get; set; }
    } // end class

} // end Models namespace

