// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using LP_API_Implementation.LpApi.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace LP_API_Implementation.LpApi
{
    [RoutePrefix("validateMember")]
    public partial class ValidateMemberController : ApiController
    {


        		/// <param name="validatememberpostrequestcontent"></param>
		/// <returns>MvResponse</returns>
        [ResponseType(typeof(MvResponse))]
        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.ValidateMemberPostRequestContent validatememberpostrequestcontent)
        {
            // Do not modify this code
            return  ((IValidateMemberController)this).Post(validatememberpostrequestcontent);
        }
    }
}
